# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.209.5/containers/javascript-node/.devcontainer/base.Dockerfile

# [Choice] Node.js version (use -bullseye variants on local arm64/Apple Silicon): 16, 14, 12, 16-bullseye, 14-bullseye, 12-bullseye, 16-buster, 14-buster, 12-buster
ARG VARIANT="16-bullseye"
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}

ENV ADB\_IP="192.168.1.101"
ENV REACT\_NATIVE\_PACKAGER\_HOSTNAME="192.168.1.103"

EXPOSE 19000
EXPOSE 19001

# [Optional] Uncomment this section to install additional OS packages.
# RUN

# [Optional] Uncomment if you want to install an additional version of node using nvm
# ARG EXTRA_NODE_VERSION=10
# RUN su node -c "source /usr/local/share/nvm/nvm.sh && nvm install ${EXTRA_NODE_VERSION}"

# [Optional] Uncomment if you want to install more global node modules
# RUN su node -c "npm install -g <your-package-list-here>"
